[package]
name = "brand/thejediorder"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.1.0-rc.2"
Signal = "sleitnick/signal@^1"
TableUtil = "sleitnick/table-util@^1"
Component = "sleitnick/component@2.0.0"
Promise = "evaera/promise@3.1.0"
Maid = "flamenco687/maid@3.2.2"
Spring = "brittonfischer/spring@0.1.0"
Loader = "sleitnick/loader@1.0.2"
Comm = "sleitnick/comm@0.1.2"
Janitor = "howmanysmall/janitor@1.13.15"
Shake = "sleitnick/shake@0.1.0"